### PR TITLE
Read fishfile from $fisher_path instead of $fish_config

### PR DESCRIPTION
**Pull request by Scrumplex**
As already discussed in #479

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by jorgebucaran** [comment]
Thanks, @Scrumplex. LGTM. I'll merge this to a different branch to keep things tidy. As discussed in #479, I want to introduce this feature in the next minor release.

**Comment by Scrumplex** [comment]
I think GitHub has an issue gmail

**Comment by jorgebucaran** [comment]
Yup 😢

**Pull request merged**
