### PR TITLE
Make curl ignore the "-w" argument. Fixes #530

### LINKED ISSUE #530: Cannot install remote plugins/prompts ( -- is this a valid package?)
Whenever I try to install a package (for example, `fisher add jorgebucaran/fish-spark`), I get the following output: `fisher: cannot add github.com/jorgebucaran/fish-spark -- is this a valid package?`. When I git clone the repo and install it locally, it works just fine.
Confusingly, the same error happened when I copied my ~/.config/fish/ to a remote machine - when I deleted that folder it worked fine. However, deleting that folder _locally_ didn't fix the issue.
I have an OMF install that potentially left remains, however I believe I've deleted mostly everything that could be loaded by fish.

Some info:
OS: Manjaro Linux
fish version 3.0.1
fisher version 3.2.7, ~/.config/fish/functions/fisher.fish

### PR DESCRIPTION
**Pull request by Scotsguy**
"Make curl display information on stdout after a completed transfer."
Intended for interactive sessions, doesn't like pipes very much

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@Scotsguy Cool. Will it change Fisher's output?

**Comment by Scotsguy** [comment]
Actually, my bad. Seems I PR'd a bit too early - this doesn't seem to work, sorry

**Comment by Scotsguy** [comment]
Sorry, I forgot this whole command is in quotes. And no, this doesn't change fisher's output from what I can tell

**Comment by jorgebucaran** [comment]
@Scotsguy So, this tells `curl` to use `""` for its -w option. It looks harmless. Let me try this out. After that, I'll merge, and cut a new release.

Thank you for all your help! 🎉

**Pull request merged**
