### PR TITLE
Updated README.md to copy the default install of tide

### PR DESCRIPTION
**Pull request by AucaCoyan**
I changed the tide install for the current install of tide in [their readme](https://github.com/IlanCosman/tide):
before:
```console
fisher install ilancosman/tide
```
after
```console
fisher install IlanCosman/tide@v5
```

### CODE REVIEW

**Comment by jorgebucaran** [comment]
Care to explain why?

**Comment by AucaCoyan** [comment]
Sorry for the delay! I wanted to fix the readme for updated installation command. 
I believe it is probable that the same user that installs fisher will also instal tide, so, to ease the path, I would copy and paste the same command of tide. Is that right?

**Comment by jorgebucaran** [comment]
Thank you, @eitsupi , I think that's the piece of info I was missing.

**Comment by jorgebucaran** [comment]
We'll need to move Tide to the second installation example, which is where we explain the use of @ to install tags or branches.

**Comment by AucaCoyan** [comment]
Thanks! You are right, I didn't explained myself correctly. I will take this as a lesson! 😄 .
l feel satisfied to close the PR. Have a nice day!

**Pull request closed without merging**
